### ISSUE TITLE
calling OPEN_MODAL multiple times is "re-displaying" the modal over and over

### ISSUE THREAD

**Issue by skuethe** [fewieden/MMM-Modal#6]
Platform (Hardware/OS):
MM² docker image
https://hub.docker.com/r/bastilimbach/docker-magicmirror

Node version:
v12.18.2

MagicMirror version:
v2.12.0

Module version:
1.0.1 as of package.json

Description of the issue:
First off, thank you for this great module! :)
I integrated this Module with MMM-Touch to display something on-screen when "tabbing" on my touchscreen (sending a `OPEN_MODAL` notification).
So far so good, this is working like a charm.
But if I just constantly "re-tab" the screen, the modal keeps re-appearing. I thought / hoped it would "toggle" the view, actually.
Looking at the following code, you seem to already close the modal if it exists on "OPEN_MODAL" notification:
https://github.com/fewieden/MMM-Modal/blob/7d6f7c515bc42403920d9dc2ea4f27939abc1247/MMM-Modal.js#L214-L217

Could this be adapted to then exit the function after closing it?
Or, going another way: would it be possible to have some "TOGGLE_MODAL" notification possible?

Thanks again for working and sharing this module! :)

**Comment by fewieden** [comment]
@skuethe I will have a look over the weekend

**Comment by fewieden** [comment]
@skuethe I already had a first look into your problem.

1. I cannot return at the mentioned code snippet. Let's imagine the following scenario:
- Someone has a confirm popup open to book an uber/lyft/...
- Then someone asks the mirror about the statistics of the running backs in the NFL
- The critical part is to close the modal first and tell the ridesharing module that the dialog was not confirmed
- Finally, it renders the new modal for the NFL

2. I also think a toggle only works for a system that only has one modal. Since this is a generic system that allows infinite modals it's not an option for me to have a toggle functionality. I rather think that the toggle mechanism should be implemented by your other module.

Could you please share your config from the module MMM-Touch, then I will think about something to make this work.

**Comment by skuethe** [comment]
Okay, that makes sense.

So the config from MMM-Touch is pretty simple and more or less irrelevant here (i think). It just sends a `WIFIPASSWORD_MODAL` notification:
https://github.com/TeraTech/MMM-WiFiPassword/pull/7#issue-496852016

This notification is then picked up by MMM-WifiPassword and triggers the OPEN_MODAL template calling:
https://github.com/TeraTech/MMM-WiFiPassword/pull/7/files#diff-e7f48a994f4db69f2fbe662b0aeb0c76R127


A possible solution could maybe be to send some additional data in the `OPEN_MODAL` notification. Some sort of "lock ID" (f.e. `this.identifier`), like they handle the `this.hide()` and `this.show()` functions:
https://docs.magicmirror.builders/development/core-module-file.html#this-show-speed-callback-options

But that is probably a "bigger" change.

Could I otherwise somehow use your [callback function](https://github.com/fewieden/MMM-Modal/blob/master/DEVELOPER.md#options) to make this work?

**Comment by fewieden** [comment]
@skuethe I made it work with the following config:

```
gestureCommands: {
                    "showWifiQr": {
                        "DOUBLE_TAP_1": (commander, gesture) => {
                            let module = commander.getModule("MMM-WiFiPassword");
                            if (module.modalActive) {
                                commander.sendNotification("WIFIPASSWORD_MODAL");
                            } else {
                                commander.sendNotification("CLOSE_MODAL");
                            }
                            module.modalActive = !module.modalActive;
                        },
                    }
                }
```
This basically saves a boolean about the current modal state. In case you have more modals and modules that close them, then you want to listen on the callback and change that variable there as well otherwise you probably run out of sync.

Another issue I found is in the getModule function of MMM-Touch. This only occurs if you have modules in your config that are disabled. I created a pull request https://github.com/gfischershaw/MMM-Touch/pull/8 for it.

**Comment by skuethe** [comment]
oh, wow. Thanks for your commitment. I'll have a look at it tomorrow

**Comment by skuethe** [comment]
Works like a charm, just one thing I changed: put the `module.modalActive = !module.modalActive;` after module declaration and before the if / else statement, otherwise the first trigger after each start / restart would be calling the "CLOSE_MODAL" even if none is showing :)

Thanks again for your support!

**Comment by fewieden** [comment]
@skuethe you're welcome, would be happy to read about your experience implementing mmm-modal in a module https://forum.magicmirror.builders/topic/9173/mmm-modal

**Comment by fewieden** [comment]
Oh and don't forget to add the module to the list here https://github.com/fewieden/MMM-Modal/wiki/Depending-Modules

**Comment by skuethe** [comment]
> 
> 
> Oh and don't forget to add the module to the list here https://github.com/fewieden/MMM-Modal/wiki/Depending-Modules

I am still waiting for the PR to go through (since it's not my module) - after that I will add it :)
